  $ cat > dune-project << EOF
  > (lang dune 3.10)
  > 
  > (package
  >  (name l))
  > EOF

  $ cat > dune << EOF
  > (library
  >  (public_name l))
  > EOF

  $ cat > l.ml << EOF
  > module M = struct
  >   type t = int
  > end
  > EOF

  $ list_docs () {
  >   find _build/default/_doc/_html/l -name '*.html' -o -name '*.html.json' | sort
  > }

  $ dune build @doc-json
  $ list_docs
  _build/default/_doc/_html/l/index.html.json
  _build/default/_doc/_html/l/l/L/M/index.html.json
  _build/default/_doc/_html/l/l/L/index.html.json

The toplevel index is generated by dune itself:

  $ cat _build/default/_doc/_html/l/index.html.json
  {"header":"<h1 id=\"l-index\"><a href=\"#l-index\" class=\"anchor\"></a>l index</h1>","type":"documentation","uses_katex":false,"breadcrumbs":[{"name":"Index","href":"../index.html","kind":"leaf-page"},{"name":"l","href":"#","kind":"page"}],"toc":[{"title":"Library l","href":"#library-l","children":[]}],"source_anchor":null,"preamble":"","content":"<h2 id=\"library-l\"><a href=\"#library-l\" class=\"anchor\"></a>Library l</h2><p>The entry point of this library is the module: <a href=\"l/L/index.html\"><code>L</code></a>.</p>"}

@doc will continue generating doc as usual:

  $ dune build @doc
  $ list_docs
  _build/default/_doc/_html/l/index.html
  _build/default/_doc/_html/l/index.html.json
  _build/default/_doc/_html/l/l/L/M/index.html
  _build/default/_doc/_html/l/l/L/M/index.html.json
  _build/default/_doc/_html/l/l/L/index.html
  _build/default/_doc/_html/l/l/L/index.html.json
